-- TuneStream cloud backend schema (Supabase/Postgres)
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  album text,
  cover_url text,
  audio_url text not null,
  duration_seconds integer,
  created_at timestamptz not null default now()
);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  cover_url text,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.playlist_tracks (
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null default 0,
  added_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (playlist_id, song_id)
);

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(requester_id, addressee_id)
);

create table if not exists public.blends (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Blend',
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.blend_members (
  blend_id uuid not null references public.blends(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (blend_id, user_id)
);

create table if not exists public.jams (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  name text not null default 'TuneStream Jam',
  status text not null default 'active' check (status in ('active','ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.jam_members (
  jam_id uuid not null references public.jams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (jam_id, user_id)
);

create table if not exists public.jam_state (
  jam_id uuid primary key references public.jams(id) on delete cascade,
  song_id bigint references public.songs(id) on delete set null,
  position_seconds numeric not null default 0,
  is_playing boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, song_id)
);

create table if not exists public.listening_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  played_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)),
          lower(regexp_replace(split_part(new.email,'@',1),'[^a-zA-Z0-9_]','','g')))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_tracks enable row level security;
alter table public.friendships enable row level security;
alter table public.blends enable row level security;
alter table public.blend_members enable row level security;
alter table public.jams enable row level security;
alter table public.jam_members enable row level security;
alter table public.jam_state enable row level security;
alter table public.likes enable row level security;
alter table public.listening_history enable row level security;
alter table public.songs enable row level security;

create policy "profiles readable by authenticated users" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

create policy "songs readable" on public.songs for select to authenticated using (true);

create policy "owners manage playlists" on public.playlists for all to authenticated
using (owner_id=auth.uid()) with check (owner_id=auth.uid());

create policy "playlist members can read tracks" on public.playlist_tracks for select to authenticated
using (exists(select 1 from public.playlists p where p.id=playlist_id and (p.owner_id=auth.uid() or p.is_public)));
create policy "playlist owners manage tracks" on public.playlist_tracks for all to authenticated
using (exists(select 1 from public.playlists p where p.id=playlist_id and p.owner_id=auth.uid()))
with check (exists(select 1 from public.playlists p where p.id=playlist_id and p.owner_id=auth.uid()));

create policy "users manage own likes" on public.likes for all to authenticated
using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "users manage own history" on public.listening_history for all to authenticated
using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy "friend requests participants" on public.friendships for all to authenticated
using (requester_id=auth.uid() or addressee_id=auth.uid())
with check (requester_id=auth.uid());

create policy "blend members" on public.blends for select to authenticated
using (created_by=auth.uid() or exists(select 1 from public.blend_members bm where bm.blend_id=id and bm.user_id=auth.uid()));
create policy "blend creator" on public.blends for insert to authenticated with check (created_by=auth.uid());
create policy "blend membership" on public.blend_members for all to authenticated
using (user_id=auth.uid() or exists(select 1 from public.blends b where b.id=blend_id and b.created_by=auth.uid()))
with check (user_id=auth.uid());

create policy "jam members access" on public.jams for select to authenticated
using (host_id=auth.uid() or exists(select 1 from public.jam_members jm where jm.jam_id=id and jm.user_id=auth.uid()));
create policy "jam host creates" on public.jams for insert to authenticated with check (host_id=auth.uid());
create policy "jam host updates" on public.jams for update to authenticated using (host_id=auth.uid()) with check (host_id=auth.uid());

create policy "jam membership access" on public.jam_members for select to authenticated
using (user_id=auth.uid() or exists(select 1 from public.jams j where j.id=jam_id and j.host_id=auth.uid()));
create policy "users join jams" on public.jam_members for insert to authenticated with check (user_id=auth.uid());

create policy "jam state members" on public.jam_state for select to authenticated
using (exists(select 1 from public.jams j left join public.jam_members jm on jm.jam_id=j.id where j.id=jam_id and (j.host_id=auth.uid() or jm.user_id=auth.uid())));
create policy "jam state members update" on public.jam_state for all to authenticated
using (exists(select 1 from public.jams j left join public.jam_members jm on jm.jam_id=j.id where j.id=jam_id and (j.host_id=auth.uid() or jm.user_id=auth.uid())))
with check (exists(select 1 from public.jams j left join public.jam_members jm on jm.jam_id=j.id where j.id=jam_id and (j.host_id=auth.uid() or jm.user_id=auth.uid())));

-- Realtime authorization for private Jam/Blend channels is enforced separately on realtime.messages.
